cors:
  origins:
    - "http://localhost:3000"
    - "https://app.openbiocure.com"
  allow_credentials: true
  allow_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
  allow_headers:
    - "*"

services:
  auth:
    url: "http://localhost:8001"
    health_endpoint: "/health"
    timeout: 30
    retries: 3

  analytics:
    url: "http://localhost:8002"
    health_endpoint: "/health"
    timeout: 30
    retries: 3

  workspace:
    url: "http://localhost:8004"
    health_endpoint: "/health"
    timeout: 30
    retries: 3
